version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: codegym
      MYSQL_DATABASE: fruit_billing
    ports:
      - "3307:3306"
    networks:
      - springboot-network

  backend:
    image: binh2408/fruit-billing-backend:1.0
    container_name: springboot-app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/fruit_billing
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: codegym
    ports:
      - "8080:8080"
    networks:
      - springboot-network

  frontend:
    image: binh2408/fruit-billing-frontend:1.0
    container_name: react-app
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
